irqchip: kvx: GENERIC_IRQ_IPI depends on CONFIG_SMP
Summary:
GENERIC_IRQ_IPI depends on CONFIG_SMP.

Without this patch:

conf_simu (not SMP) fails with:

```
kernel/irq/ipi.c: In function ‘irq_reserve_ipi’:
kernel/irq/ipi.c:94:42: error: ‘struct irq_common_data’ has no member named ‘affinity’
   94 |                 cpumask_copy(data->common->affinity, dest);
      |                                          ^~
make[4]: *** [kernel/irq/ipi.o] Error 1
```

Ref T20145

Test Plan: CI

Reviewers: O51 Linux Coolidge!

Subscribers: #linux_coolidge_cc

Maniphest Tasks: T20145

Differential Revision: https://phab.kalray.eu/D29814